schema_version = "1.0.0"
id = "Pickwalk"
version = "1.0.0"
name = "Pick Walk"
tagline = "Pick walk for vetices and faces"
maintainer = "Blender Bob"
type = "add-on"
website = "https://github.com/riouxr/Pickwalk"
tags = ["Mesh"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2025 Robert Rioux"]